### ISSUE TITLE
[BUG] Unit tests fail with "Cannot find module 'sinon'"

### ISSUE THREAD

**Issue by ArcadeCityMayor** [Cameri/nostream#112]
**Describe the bug**
A fresh `git clone` and `npm i` of this repo has unit tests fail with `Error: Cannot find module 'sinon'`

**To Reproduce**
1.`git clone git@github.com:Cameri/nostream.git`
2. `cd nostream`
3. `npm i`
4. `npm run test:unit`

**Expected behavior**
Tests to pass without installing an additional package

**System (please complete the following information):**
 - macOS Ventura 13.0.1
 - Platform: standalone
 - Version: 1.15.0

**Logs**
```
nostream git:(main) ✗ npm run test:unit

> nostream@1.15.0 pretest:unit
> mkdir -p .test-reports/unit


> nostream@1.15.0 test:unit
> mocha 'test/**/*.spec.ts'


Error: Cannot find module 'sinon'
Require stack:
- /Users/christopherdavid/code/nostream/test/unit/factories/settings-factory.spec.ts
- /Users/christopherdavid/code/nostream/node_modules/mocha/lib/nodejs/esm-utils.js
- /Users/christopherdavid/code/nostream/node_modules/mocha/lib/mocha.js
- /Users/christopherdavid/code/nostream/node_modules/mocha/lib/cli/one-and-dones.js
- /Users/christopherdavid/code/nostream/node_modules/mocha/lib/cli/options.js
- /Users/christopherdavid/code/nostream/node_modules/mocha/bin/mocha
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/Users/christopherdavid/code/nostream/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/christopherdavid/code/nostream/test/unit/factories/settings-factory.spec.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module.m._compile (/Users/christopherdavid/code/nostream/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/christopherdavid/code/nostream/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.exports.requireOrImport (/Users/christopherdavid/code/nostream/node_modules/mocha/lib/nodejs/esm-utils.js:60:20)
    at async Object.exports.loadFilesAsync (/Users/christopherdavid/code/nostream/node_modules/mocha/lib/nodejs/esm-utils.js:103:20)
    at async singleRun (/Users/christopherdavid/code/nostream/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at async Object.exports.handler (/Users/christopherdavid/code/nostream/node_modules/mocha/lib/cli/run.js:374:5)
```

**Additional context**
Tests ran and passed fine after running `npm i -D sinon`, so sinon probably just needs to be added to package.json devDependencies.

**Comment by Cameri** [comment]
Woah, I wonder how/when it got removed...
