### ISSUE TITLE
[BUG] Unable confirm invoice

### ISSUE THREAD

**Issue by Cameri** [Cameri/nostream#193]
**Describe the bug**
Unable to confirm invoice because it is pending.

**To Reproduce**
TBD

**Expected behavior**
Invoice is either not confirmed or ignored.

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - Platform: [e.g. docker, standalone]
 - Version: [e.g. 1.9.11]

**Logs**
If applicable, attach log messages showing the bug and context when the bug happened.

```
Unable to update invoice. Reason: error: insert into "invoices" ("amount_requested", "bolt11", "created_at", "description", "expires_at", "id", "pubkey", "status", "unit", "updated_at") values ($1, DEFAULT, DEFAULT, $2, DEFAULT, $3, $4, $5, $6, $7) on conflict ("id") do update set "status" = $8,"updated_at" = $9 - null value in column "bolt11" of relation "invoices" violates not-null constraint
    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 478,
  severity: 'ERROR',
  code: '23502',
  detail: 'Failing row contains (ece279c3-7e88-44cc-87b3-94010eedc5eb, \\x0000006a13e10fb648049b5e78632a0c2bf09eaf6a9d55d081b82baf86c951..., null, 5000000, null, msats, expired, eden.nostr.land Admission Fee for npub1qqqqq6snuy8mvjqynd08sce2p..., null, null, 2023-02-10 22:55:39.346619+00, 2023-02-10 22:55:39.335+00).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'invoices',
  column: 'bolt11',
  dataType: undefined,
  constraint: undefined,
  file: 'execMain.c',
  line: '1883',
  routine: 'ExecConstraints'
}
Unable to persist invoice ece279c3-7e88-44cc-87b3-94010eedc5eb error: insert into "invoices" ("amount_requested", "bolt11", "created_at", "description", "expires_at", "id", "pubkey", "status", "unit", "updated_at") values ($1, DEFAULT, DEFAULT, $2, DEFAULT, $3, $4, $5, $6, $7) on conflict ("id") do update set "status" = $8,"updated_at" = $9 - null value in column "bolt11" of relation "invoices" violates not-null constraint
    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 478,
  severity: 'ERROR',
  code: '23502',
  detail: 'Failing row contains (ece279c3-7e88-44cc-87b3-94010eedc5eb, \\x0000006a13e10fb648049b5e78632a0c2bf09eaf6a9d55d081b82baf86c951..., null, 5000000, null, msats, expired, eden.nostr.land Admission Fee for npub1qqqqq6snuy8mvjqynd08sce2p..., null, null, 2023-02-10 22:55:39.346619+00, 2023-02-10 22:55:39.335+00).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'invoices',
  column: 'bolt11',
  dataType: undefined,
  constraint: undefined,
  file: 'execMain.c',
  line: '1883',
  routine: 'ExecConstraints'
}
uncaught error: TypeError: invalid media type
    at Object.parse (/app/node_modules/content-type/index.js:126:11)
    at setCharset (/app/node_modules/express/lib/utils.js:254:28)
    at ServerResponse.send (/app/node_modules/express/lib/response.js:174:32)
    at postZebedeeCallbackRequestHandler (/app/src/handlers/request-handlers/post-zebedee-callback-request-handler.js:14:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

```
Unable to confirm invoice. Reason: Error: Invoice is not complete: pending
    at PaymentsService.confirmInvoice (/app/src/services/payments-service.js:120:23)
    at MaintenanceWorker.onSchedule (/app/src/app/maintenance-worker.js:51:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Unable to update invoice from payment processor. Reason: Error: Unable to get transaction: transaction not started.
    at Transaction.rollback (/app/src/database/transaction.js:27:19)
    at PaymentsService.confirmInvoice (/app/src/services/payments-service.js:149:31)
    at MaintenanceWorker.onSchedule (/app/src/app/maintenance-worker.js:51:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Additional context**

**Comment by Cameri** [comment]
Fixed in #204
