### ISSUE TITLE
Unexpected Token when starting relay

### ISSUE THREAD

**Issue by seanmurphy1661** [Cameri/nostream#339]
https://github.com/Cameri/nostream/blob/3b5b1fc85fbd5ba59711bb83189f06926a141d13/src/app/app.ts#L75C15-L75C15

```
npm run start

> nostream@1.25.2 prestart
> npm run build


> nostream@1.25.2 build
> tsc --project tsconfig.build.json


> nostream@1.25.2 start
> cd dist && node src/index.js

/home/ubuntu/nostream/dist/src/app/app.js:66
            : this.settings().workers?.count || (0, os_1.cpus)().length;
                                      ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/ubuntu/nostream/dist/src/factories/app-factory.js:9:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

```

**Comment by Cameri** [comment]
@seanmurphy1661 what is your `node` and `npm` version? Use `node -v` and `npm -v` to get it.
Make sure Node is at least v18.8.0.

**Comment by seanmurphy1661** [comment]
I think it was, but I don't have that environment around anymore. I will close it for now. If it happens again, i'll repost with better info.
